### ISSUE TITLE
error shutdown command

### ISSUE THREAD

**Issue by Lobooooooo14** [Ravost99/Disnake.py-Bot-Template#1]
hi i was testing the commands   `.is_owner()` that you kept in the repository and I noticed a small error in the shutdown command:
```python
    async def shutdown(self, inter):
        embed = disnake.Embed(
          title="Logging out",
          description=":wave: Goodbye!",
          color=config.success
        )
        await inter.send(embed=embed)
        await self.bot.logout()
```
happens that `await self.bot.logout()` causes an error, however, to solve this problem is very simple, just replace:
```python
await self.bot.logout()
```
per:
```python
await self.bot.close()
```
I'm not sure if this was a version change or something, but it worked for me.

**Comment by Ravost99** [comment]
Thanks it works!
